version: '3.1'

services:
  products:
    build: .
    depends_on:
      - 'db'
    ports:
      - '8080:80'
    volumes:
      -  /home/alex/hr/sdc/sdc-products/:/src/app

  db:
    image: postgres:latest
    volumes:
      - /home/alex/hr/sdc/sdc-database/data:/var/lib/postgresql/data
      - /home/alex/hr/sdc/sdc-database/raw:/raw
      - /home/alex/hr/sdc/sdc-products/:/app
      - /home/alex/hr/sdc/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products_api
    command: -c 'config_file=/app/postgresql.conf'
