version: '3.1'

services:
  products:
    build: .
    depends_on:
      - 'db'
    ports:
      - '80:80'
    environment:
      NODE_ENV: production
        #volumes:
            #  - /srv/sdc:/src/app

  db:
    image: postgres:latest
    volumes:
      - /srv/db:/var/lib/postgresql/data
      - /raw:/raw
      - /srv/sdc/:/app
      - /srv/docker:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products_api
    command: -c 'config_file=/app/postgresql.conf'
